#
#
#
#        Reports & Punishments - Premium plugin for Play Games
#            Check out Play Games @ https://play-gam.es/
#             Join the discord @ discord.gg/playgames
#                     Coded by Jay & Nicolas
#
#
#

Plugin:
  Prefix:
    Reports: '&#FB7800&lReports &8➟'
    Punishments: '&#FB1515&lPunishments &8➟'
  Database:
    Type: 'H2'
    Address: 'localhost'
    Port: '3306'
    Username: 'root'
    Password: '********'
    DatabaseName: 'db_pg_1'

Messages:
  Reports:
    Player:
      Report-Created: '&#22F100You have reported &f%target% &#22F100and it was sent to staff.'
      Duplicate-Report: '&#FF1B1BReport for &f%target% &#FF1B1Balready exists.'
    Staff:
      Report-Created: '&f%player% &#FF1B1Bhas reported &f%target% &#FF1B1Bfor &f%reason%.'
      Report-Assigned: '&#22F100You are now handling a report against &f%current_active_report%'
      Report-Clear: '&#FF1B1BYou have cleared reports for &f%current_active_report%'

StaffMode:
  Vanish: true
  Spectator: true
  TP-Back: true
  Inventory:
    '0':
      Item: 'ENDER_PEARL'
      DisplayName: '&#1BBAFF&lTeleport To: &f&n%current_active_report%.'
      Slot: 0
      Lore:
        - '&7By using this item you will teleport to the player!'
        - ''
        - '&eRight-Click to Use!'
      Glowing: true
      Commands:
        - 'tp %player%'
    '1':
      Item: 'NETHER_STAR'
      DisplayName: '&#FB1515&lPunish: &f&n%current_active_report%.'
      Slot: 4
      Lore:
        - '&7By using this item you will teleport to the player!'
        - ''
        - '&eRight-Click to Use!'
      Glowing: true
      Commands:
        - 'punish %current_active_report%'
    '2':
      Item: 'BEACON'
      DisplayName: '&#22F100&lClear Reports: &f&n%current_active_report%.'
      Slot: 8
      Lore:
        - ''
        - ''
        - ''
        - ''
      Glowing: true
      Commands:
        - 'report clear %current_active_report%'
    '3':
      Item: 'ICE'
      DisplayName: '&#13E3FF&lFreeze: &f&n%current_active_report%.'
      Slot: 3
      Lore:
        - ''
        - ''
        - ''
        - ''
      Glowing: true
      Commands:
        - 'freeze %current_active_player%'




Errors:
  NoPlayer: '&cNo Player Found.'
  NoPermission: '&cNo Permission.'
  InvalidArguments: '&cNo such command. try /reports help.'